<x-layout title="Keranjang">
<div class="container cart-page"><div class="eyebrow">PESANAN KAMU</div><h1>Keranjang</h1>
@if(session('success'))<div class="notice success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="notice error" role="alert">{{ $errors->first() }}</div>@endif
@if($products->isEmpty())<div class="empty-panel"><h2>Keranjang masih kosong</h2><p>Jelajahi katalog dan pilih barang yang kamu inginkan.</p><a class="button accent" href="{{ route('home') }}#produk">Lihat produk</a></div>
@else<div class="cart-layout"><div class="cart-lines panel"><h2>{{ $products->count() }} jenis barang</h2>
@foreach($products as $product)<div class="cart-line"><a class="cart-line-photo" href="{{ route('products.show',$product) }}">@if($product->cover_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($product->cover_path) }}" alt="{{ $product->name }}">@else<span>FOTO</span>@endif</a><div class="cart-line-info"><a href="{{ route('products.show',$product) }}"><strong>{{ $product->name }}</strong></a><span>Rp {{ number_format($product->price,0,',','.') }} / item</span><small>{{ $product->status==='published'?'Stok tersedia: '.$product->stock:'Saat ini tidak tersedia' }}</small></div><div class="cart-line-actions"><form method="post" action="{{ route('cart.update',$product->id) }}">@csrf @method('PATCH')<label class="sr-only" for="qty-{{ $product->id }}">Jumlah {{ $product->name }}</label><input id="qty-{{ $product->id }}" name="quantity" type="number" min="1" max="10" value="{{ $quantities[$product->id] }}"><button type="submit" class="text-button">Ubah</button></form><form method="post" action="{{ route('cart.remove',$product->id) }}">@csrf @method('DELETE')<button type="submit" class="text-button danger">Hapus</button></form></div></div>@endforeach
</div><form method="post" action="{{ route('orders.store') }}" class="panel cart-checkout">@csrf<input type="hidden" name="mode" value="cart"><h2>Pengiriman & pembayaran</h2><div class="cart-total"><span>Subtotal barang</span><strong>Rp {{ number_format($subtotal,0,',','.') }}</strong></div><p class="fine-print">Ongkir dikonfirmasi pengelola sesuai alamat dan layanan yang dipilih.</p><label>Nama penerima<input name="customer_name" required value="{{ old('customer_name') }}" autocomplete="name"></label><label>Nomor WhatsApp<input name="customer_phone" required value="{{ old('customer_phone') }}" inputmode="tel" autocomplete="tel"></label><label>Alamat lengkap<textarea name="shipping_address" rows="3" minlength="10" maxlength="2000" required placeholder="Jalan, nomor, RT/RW, kelurahan, kecamatan, kota, provinsi, kode pos">{{ old('shipping_address') }}</textarea></label><label>Pengiriman<select name="shipping_method" required><option value="">Pilih layanan</option>@foreach(\App\Models\Order::SHIPPING_METHODS as $code=>$label)<option value="{{ $code }}" @selected(old('shipping_method')===$code)>{{ $label }}</option>@endforeach</select></label><button class="button accent full" type="submit">Checkout & lihat QRIS →</button></form></div>@endif
</div>
</x-layout>
